// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnowyRiver.Accounts.Manager.EntityFramework;

#nullable disable

namespace SnowyRiver.Accounts.Manager.EntityFramework.Migrations
{
    [DbContext(typeof(AccountsManagerDbContext))]
    [Migration("20260414021330_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Accounts_RolePermissions", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("Accounts_RolePermissions");
                });

            modelBuilder.Entity("Accounts_UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts_UserRoles");
                });

            modelBuilder.Entity("Accounts_UserTeams", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("Accounts_UserTeams");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("Accounts_Permissions", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.PermissionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapShotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("SnapShotId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts_PermissionHistories", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("Accounts_Roles", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.RoleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapShotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("SnapShotId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts_RoleHistories", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("Accounts_Teams", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.TeamHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapShotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("SnapShotId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts_TeamHistories", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("Accounts_Users", (string)null);
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.UserHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifierUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapShotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorTeamId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifierTeamId");

                    b.HasIndex("LastModifierUserId");

                    b.HasIndex("SnapShotId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts_UserHistories", (string)null);
                });

            modelBuilder.Entity("Accounts_RolePermissions", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts_UserRoles", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounts_UserTeams", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Permission", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Permission", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.PermissionHistory", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Permission", "SnapShot")
                        .WithMany()
                        .HasForeignKey("SnapShotId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");

                    b.Navigation("SnapShot");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Role", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.RoleHistory", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Role", "SnapShot")
                        .WithMany()
                        .HasForeignKey("SnapShotId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");

                    b.Navigation("SnapShot");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Team", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.TeamHistory", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "SnapShot")
                        .WithMany()
                        .HasForeignKey("SnapShotId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");

                    b.Navigation("SnapShot");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.User", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.UserHistory", b =>
                {
                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "CreatorTeam")
                        .WithMany()
                        .HasForeignKey("CreatorTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "LastModifierTeam")
                        .WithMany()
                        .HasForeignKey("LastModifierTeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "SnapShot")
                        .WithMany()
                        .HasForeignKey("SnapShotId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("SnowyRiver.Accounts.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CreatorTeam");

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifierTeam");

                    b.Navigation("LastModifierUser");

                    b.Navigation("SnapShot");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnowyRiver.Accounts.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
